-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.area
(
    idarea integer NOT NULL,
    descripcion character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT area_pkey PRIMARY KEY (idarea)
);

CREATE TABLE IF NOT EXISTS public.comentarios
(
    idcomentario integer NOT NULL,
    idlogro integer,
    idusuario integer,
    descripcion character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT comentarios_pkey PRIMARY KEY (idcomentario)
);

CREATE TABLE IF NOT EXISTS public.likeslogro
(
    idlike integer NOT NULL,
    idlogro integer,
    idusuario integer,
    CONSTRAINT likeslogro_pkey PRIMARY KEY (idlike)
);

CREATE TABLE IF NOT EXISTS public.logro
(
    idlogro integer NOT NULL,
    fecha date,
    descripcion character varying(200) COLLATE pg_catalog."default",
    imagen character varying(200) COLLATE pg_catalog."default",
    idarea integer NOT NULL,
    idusuario integer NOT NULL,
    visible boolean,
    CONSTRAINT logro_pkey PRIMARY KEY (idlogro)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    idusuario integer NOT NULL,
    correo character varying(200) COLLATE pg_catalog."default",
    fechanacimiento date,
    nombreusuario character varying(50) COLLATE pg_catalog."default",
    pass character varying(50) COLLATE pg_catalog."default",
    imagen character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT usuario_pkey PRIMARY KEY (idusuario)
);

ALTER TABLE IF EXISTS public.comentarios
    ADD CONSTRAINT comentarios_idlogro_fkey FOREIGN KEY (idlogro)
    REFERENCES public.logro (idlogro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.comentarios
    ADD CONSTRAINT comentarios_idusuario_fkey FOREIGN KEY (idusuario)
    REFERENCES public.usuario (idusuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.likeslogro
    ADD CONSTRAINT fk_usuario FOREIGN KEY (idusuario)
    REFERENCES public.usuario (idusuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.likeslogro
    ADD CONSTRAINT likeslogro_idlogro_fkey FOREIGN KEY (idlogro)
    REFERENCES public.logro (idlogro) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.logro
    ADD CONSTRAINT logro_idarea_fkey FOREIGN KEY (idarea)
    REFERENCES public.area (idarea) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.logro
    ADD CONSTRAINT logro_idusuario_fkey FOREIGN KEY (idusuario)
    REFERENCES public.usuario (idusuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
 v
END;